import type { Metadata, Viewport } from "next"
import { Inter } from "next/font/google"

import "@/globals.css"

import { cn } from "@/lib/utils"
import Header from "@/components/Header"
import { Providers } from "@/components/Providers"

const inter = Inter({
  subsets: ["latin"],
  display: "swap",
  variable: "--font-sans",
})

export const experimental_ppr = true

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export const viewport: Viewport = {
  themeColor: [
    { media: "(prefers-color-scheme: light)", color: "#FEFEFE" },
    { media: "(prefers-color-scheme: dark)", color: "#121212" },
  ],
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={cn(
          "bg-background font-sans text-foreground antialiased",
          inter.variable
        )}
      >
        <Providers>
          <Header />
          <main className="p-4 sm:p-8">{children}</main>
        </Providers>
      </body>
    </html>
  )
}
